var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/pengumuman/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p712f.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w07ooo.js")
R.c("server/chunks/ssr/[root-of-the-server]__056gqu7._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ba~x_l._.js")
R.c("server/chunks/ssr/_0je8wg_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0flqau8._.js")
R.c("server/chunks/ssr/_05vn1qf._.js")
R.c("server/chunks/ssr/_0r07mm7._.js")
R.c("server/chunks/ssr/_0rp8bt3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_pengumuman_page_actions_0651oav.js")
R.m(62223)
module.exports=R.m(62223).exports
