// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/announcements" | "/admin/announcements/[id]" | "/admin/announcements/new" | "/admin/articles" | "/admin/articles/[id]" | "/admin/articles/new" | "/admin/aspirations" | "/admin/divisions" | "/admin/downloads" | "/admin/gallery" | "/admin/history" | "/admin/leaders" | "/admin/login" | "/admin/media" | "/admin/pages" | "/admin/pages/[pageKey]" | "/admin/programs" | "/admin/settings" | "/admin/users" | "/agenda" | "/arsip" | "/aspirasi" | "/berita" | "/berita/[slug]" | "/divisi" | "/divisi/[slug]" | "/galeri" | "/kepengurusan" | "/kontak" | "/lab/backdrop" | "/pengumuman" | "/pengurus/[slug]" | "/program-kerja" | "/program-kerja/[slug]" | "/template-dokumen" | "/unduhan"
type AppRouteHandlerRoutes = "/api/admin/accounts" | "/api/imagekit-auth" | "/api/imagekit-file" | "/api/revalidate"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/announcements": {}
  "/admin/announcements/[id]": { "id": string; }
  "/admin/announcements/new": {}
  "/admin/articles": {}
  "/admin/articles/[id]": { "id": string; }
  "/admin/articles/new": {}
  "/admin/aspirations": {}
  "/admin/divisions": {}
  "/admin/downloads": {}
  "/admin/gallery": {}
  "/admin/history": {}
  "/admin/leaders": {}
  "/admin/login": {}
  "/admin/media": {}
  "/admin/pages": {}
  "/admin/pages/[pageKey]": { "pageKey": string; }
  "/admin/programs": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/agenda": {}
  "/api/admin/accounts": {}
  "/api/imagekit-auth": {}
  "/api/imagekit-file": {}
  "/api/revalidate": {}
  "/arsip": {}
  "/aspirasi": {}
  "/berita": {}
  "/berita/[slug]": { "slug": string; }
  "/divisi": {}
  "/divisi/[slug]": { "slug": string; }
  "/galeri": {}
  "/kepengurusan": {}
  "/kontak": {}
  "/lab/backdrop": {}
  "/pengumuman": {}
  "/pengurus/[slug]": { "slug": string; }
  "/program-kerja": {}
  "/program-kerja/[slug]": { "slug": string; }
  "/template-dokumen": {}
  "/unduhan": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
