// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/(protected)/announcements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/announcements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/announcements/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/announcements/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/articles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/articles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/articles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/articles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/articles/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/articles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/articles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/articles">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/articles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/aspirations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/aspirations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/aspirations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/data/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/data/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/data/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/data/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/divisions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/divisions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/divisions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/downloads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/downloads">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/downloads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/history">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/leaders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leaders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/leaders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/pages/[pageKey]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages/[pageKey]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/pages/[pageKey]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/programs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(protected)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agenda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agenda">> = Specific
  const handler = {} as typeof import("../../src/app/agenda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/arsip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arsip">> = Specific
  const handler = {} as typeof import("../../src/app/arsip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/aspirasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aspirasi">> = Specific
  const handler = {} as typeof import("../../src/app/aspirasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/berita/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/berita/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/berita/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/berita/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/berita">> = Specific
  const handler = {} as typeof import("../../src/app/berita/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/data/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data">> = Specific
  const handler = {} as typeof import("../../src/app/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/divisi/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/divisi/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/divisi/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/divisi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/divisi">> = Specific
  const handler = {} as typeof import("../../src/app/divisi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galeri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galeri">> = Specific
  const handler = {} as typeof import("../../src/app/galeri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kepengurusan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kepengurusan">> = Specific
  const handler = {} as typeof import("../../src/app/kepengurusan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kontak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kontak">> = Specific
  const handler = {} as typeof import("../../src/app/kontak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lab/backdrop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/backdrop">> = Specific
  const handler = {} as typeof import("../../src/app/lab/backdrop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pengumuman/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pengumuman">> = Specific
  const handler = {} as typeof import("../../src/app/pengumuman/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pengurus/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pengurus/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/pengurus/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/program-kerja/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/program-kerja/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/program-kerja/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/program-kerja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/program-kerja">> = Specific
  const handler = {} as typeof import("../../src/app/program-kerja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/template-dokumen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/template-dokumen">> = Specific
  const handler = {} as typeof import("../../src/app/template-dokumen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unduhan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unduhan">> = Specific
  const handler = {} as typeof import("../../src/app/unduhan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imagekit-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imagekit-auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/imagekit-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imagekit-file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imagekit-file">> = Specific
  const handler = {} as typeof import("../../src/app/api/imagekit-file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../src/app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
